name: pystran
dependencies:
- alabaster=0.7.6
- astroid=1.3.4
- babel=2.1.1
- backports_abc=0.4
- cairo=1.12.18
- cycler=0.9.0
- decorator=4.0.4
- docutils=0.12
- fontconfig=2.11.1
- freetype=2.5.5
- ipykernel=4.1.1
- ipython=4.0.1
- ipython-notebook=4.0.4
- ipython_genutils=0.1.0
- jedi=0.9.0
- jinja2=2.8
- jsonschema=2.4.0
- jupyter_client=4.1.1
- jupyter_core=4.0.6
- libgfortran=1.0
- libpng=1.6.17
- libsodium=1.0.3
- libxml2=2.9.2
- logilab-common=0.63.2
- markupsafe=0.23
- matplotlib=1.5.0
- mistune=0.7.1
- nbconvert=4.0.0
- nbformat=4.0.1
- notebook=4.0.6
- numpy=1.10.1
- openblas=0.2.14
- openssl=1.0.2d
- pandas=0.17.1
- path.py=8.1.2
- pep8=1.6.2
- pexpect=3.3
- pickleshare=0.5
- pip=7.1.2
- pixman=0.32.6
- psutil=3.3.0
- ptyprocess=0.5
- py2cairo=1.10.0
- pyflakes=1.0.0
- pygments=2.0.2
- pylint=1.4.2
- pyparsing=2.0.3
- pyqt=4.11.4
- python=2.7.11
- python-dateutil=2.4.2
- pytz=2015.7
- pyzmq=14.7.0
- qt=4.8.7
- qtconsole=4.1.1
- readline=6.2
- rope=0.9.4
- scipy=0.16.0
- setuptools=18.5
- simplegeneric=0.8.1
- singledispatch=3.4.0.3
- sip=4.16.9
- six=1.10.0
- snowballstemmer=1.2.0
- sphinx=1.3.1
- sphinx_rtd_theme=0.1.7
- spyder=2.3.8
- sqlite=3.8.4.1
- ssl_match_hostname=3.4.0.2
- terminado=0.5
- tk=8.5.18
- tornado=4.3
- traitlets=4.0.0
- wheel=0.26.0
- zeromq=4.1.3
- zlib=1.2.8
- pip:
  - backports-abc==0.4
  - backports.ssl-match-hostname==3.4.0.2
  - ipython-genutils==0.1.0
  - jupyter-client==4.1.1
  - jupyter-core==4.0.6
  - pystran (/media/DATA/Githubs/pystran)==0.1
  - sphinx-rtd-theme==0.1.7
